Repository AgnostiqHQ/covalent-slurm-plugin, pull requests merged in 2022-04, with the labels that each got.

#6 global variable string change
  .github/workflows/tests.yml
  CHANGELOG.md
  VERSION
  covalent_slurm_plugin/slurm.py
Labels: improvements / style

#10 add time module import back
  CHANGELOG.md
  VERSION
  covalent_slurm_plugin/slurm.py
Labels: bug :bug:

#13 Better function transport
  CHANGELOG.md
  VERSION
  covalent_slurm_plugin/slurm.py
Labels: bug :bug:

#15 Add tests
  .github/workflows/tests.yml
  CHANGELOG.md
  VERSION
  tests/requirements.txt
  tests/slurm_tests.py
Labels: testing, testing / unit tests
